### ISSUE TITLE
exponent-to-prefix fails for no prefix when computation is required

### ISSUE THREAD

**Issue by bkuczenski** [josephwright/siunitx#299] opened 2016-11-29 08:05 UTC
\documentclass[12pt,letterpaper]{article}

    \usepackage{siunitx}
    \sisetup{scientific-notation=engineering, 
      exponent-to-prefix=true}

    \begin{document}

    works: \SI{3}{\meter}

    does not work: \SI{0.003}{\kilo\meter}

    \end{document}

Using version 2016/03/01 v2.6q, so perhaps it has been fixed?

#297 also mentions a case when no prefix is required.

**Comment by josephwright** [comment] 2016-11-29 09:55
There are a few of these 'timing' question, and I think my normal response applies here. The options apply to the _input_, which as the error says doesn't have any exponent part.  I'm working on v3 and will probably revisit this type of issue there, but for v2 I'm unlikely to fiddle with the code.

**Comment by josephwright** [comment] 2021-04-05 09:57
This is fixed in v3: plan is to get that out in the summer.

**Closed** 2021-04-05 11:02 UTC
Labels: bug, fixed-in-v3

**Comment by Bosef1** [comment] 2021-05-25 02:06
Part of the problem is that SI doesn't define a magnitude prefix between deca- and deci that means 10^0=1.  For people who still need to use siunitx Version 2 for compatibility reasons, try defining a magnitude 1 prefix that doesn't print anything.  For example, something like this:
`\DeclareSIPrefix\nona{}{0}`
This creates the SI prefix 'nona' that doesn't print anything (first set of empty braces), and has a value of 10^0=1 (second {0} braces).

It might be worthwhile to create a proposal to BIPM to add a unitary prefix to the SI prefixes for the sake of consistency.
