### ISSUE TITLE
Separate input uncertainties parsed incorrectly (missing digits) for values with fewer decimals

### ISSUE THREAD

**Issue by Socob** [josephwright/siunitx#354] opened 2018-12-27 23:49 UTC
If numbers with uncertainties are input using the `\SI{1.23 +- 0.04}{\m}` or `\num{1.23 +- 0.04}` syntax, the resulting uncertainties in the output are **incorrect** if trailing decimal zeros are omitted for the value. To be precise, it seems that the value can *at most* have one fewer decimal digit than the number given as the uncertainty. For example, `\num{2.0 +- 0.0051}` outputs `2.000(51)`, which is wrong!

Here is a minimal example (using `siunitx` v2.7s):

```
\documentclass{article}
\usepackage{siunitx}

\begin{document}

\twocolumn
\setlength{\parindent}{0pt}

\num{2 +- 0.0051}
\textbf{wrong!}\\
\SI{2 +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\num{2. +- 0.0051}
\textbf{wrong!}\\
\SI{2. +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\num{2.0 +- 0.0051}
\textbf{wrong!}\\
\SI{2.0 +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\hrule
\par\medskip
\num{2 +- 0.051}
\textbf{wrong!}\\
\SI{2 +- 0.051}{\m}
\textbf{wrong!}
\par\medskip
\num{2. +- 0.051}
\textbf{wrong!}\\
\SI{2. +- 0.051}{\m}
\textbf{wrong!}
\par\medskip
\num{2.0 +- 0.051}\\
\SI{2.0 +- 0.051}{\m}
\par\medskip
\hrule
\par\medskip
\num{2 +- 0.51}\\
\SI{2 +- 0.51}{\m}
\par\medskip
\num{2. +- 0.51}\\
\SI{2. +- 0.51}{\m}
\par\medskip
\num{2.0 +- 0.51}\\
\SI{2.0 +- 0.51}{\m}

\newpage

\sisetup{separate-uncertainty}

\num{2 +- 0.0051}
\textbf{wrong!}\\
\SI{2 +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\num{2. +- 0.0051}
\textbf{wrong!}\\
\SI{2. +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\num{2.0 +- 0.0051}
\textbf{wrong!}\\
\SI{2.0 +- 0.0051}{\m}
\textbf{wrong!}
\par\medskip
\hrule
\par\medskip
\num{2 +- 0.051}
\textbf{wrong!}\\
\SI{2 +- 0.051}{\m}
\textbf{wrong!}
\par\medskip
\num{2. +- 0.051}
\textbf{wrong!}\\
\SI{2. +- 0.051}{\m}
\textbf{wrong!}
\par\medskip
\num{2.0 +- 0.051}\\
\SI{2.0 +- 0.051}{\m}
\par\medskip
\hrule
\par\medskip
\num{2 +- 0.51}\\
\SI{2 +- 0.51}{\m}
\par\medskip
\num{2. +- 0.51}\\
\SI{2. +- 0.51}{\m}
\par\medskip
\num{2.0 +- 0.51}\\
\SI{2.0 +- 0.51}{\m}

\end{document}
```

---

*Remark:* I’ve run into a very similar issue with missing digits in uncertainties some years ago, but before I could report it, a newer version of `siunitx` seemed to fix it. However, I couldn’t find anything similar reported as an issue here. I do hope it was just fixed “silently” and we haven’t been stuck with a nasty bug like this for years.

**Comment by josephwright** [comment] 2018-12-28 08:40
Duplicate of https://github.com/josephwright/siunitx/issues/261.

**Closed by josephwright** 2018-12-28 08:40 UTC
Labels: bug
