### ISSUE TITLE
Incompatibility with package realscripts

### ISSUE THREAD

**Issue by Epaulard** [josephwright/siunitx#597] opened 2022-03-16 19:55 UTC
Hi

Thanks a lot for this great package.

When compiled with LuaTex the code hereafter shows an issue. 
With the last command  the minus sign looks like underscore sign. 
It's OK when realscripts package is **not** loaded.
Unfortunately, I use widely this package.

Is this issue with Erewhon font or siunitx ?

`\documentclass{article}
\usepackage{fontspec}
\setmainfont{Erewhon}
\usepackage[mode=match]{siunitx}
\usepackage{realscripts}
\begin{document}
$\num{e-2}$ OK

10\textsuperscript{-2} OK

{10{\addfontfeature{VerticalPosition=Superior}{-2}}} OK

\num{e-2} KO
\end{document}`

**Comment by josephwright** [comment] 2022-03-16 20:03
It's ... complicated. The way that `realscripts` works is to redefine `\textsuperscript`, and then use positional variants for the text. However, depending on the font, it's possible that not all of the glyphs will look right. I've already got a changed checked in that covers that: 7eb78360f2e4cfbe65d86120b0d5808b8606eb72. That is an API extension, as this really isn't a bug in `siunitx`. That change will allow you to tell `siunitx` to (effectively) disable `realscripts` for textual superscripts from units. However, even then I can't automate: depending on which glyphs you happen to use, this may or may not be needed.

**Comment by josephwright** [comment] 2022-03-16 20:03
Duplicate of https://github.com/josephwright/siunitx/issues/595.

**Closed by josephwright** 2022-03-16 20:03 UTC
Labels: duplicate, enhancement

**Comment by Epaulard** [comment] 2022-03-16 21:32
I agree, this is a duplicate of #595 
Thanks for the swift reply
