### ISSUE TITLE
Documentation: Lacks Discussion of Rounding With Uncertainties

### ISSUE THREAD

**Issue by odysseus9672** [josephwright/siunitx#267] opened 2015-04-30 00:54 UTC
First, let me say that this package looks like a real boon for scientists who deal with numbers. Looking through the documentation, though, there's no description of how rounding is handled in the presence of uncertainties. In my mind, the only approach that makes sense is to specify the number of significant figures to round the uncertainty to, and then round digits off of the main quantity that are less significant than the digits rounded off the uncertainty. 

There is, however, no mention in the documentation of if this is done or a way to specify how to round the uncertainty (which then controls the rounding of the main quantity).

**Comment by josephwright** [comment] 2017-02-06 17:59
I'm looking at the for v3. Currently I'm getting my ideas together but you are likely right with one minor exception: typically one doesn't use `(1)` but rather `(1n)` where `n` is a single positive digit. I guess I'll try to cover that with a couple of settings.

**Comment by odysseus9672** [comment] 2017-02-06 18:39
I implemented a small rounding package in Python that behaves the way I had in mind.

https://github.com/odysseus9672/SELPythonLibs/blob/master/SigFigRounding.py

**Comment by josephwright** [comment] 2018-06-18 08:41
I realise that this is a duplicate of https://github.com/josephwright/siunitx/issues/179.

**Closed by josephwright** 2018-06-18 08:41 UTC
Labels: duplicate, enhancement
