### ISSUE TITLE
! Undefined control sequence. \__siunitx_font_weight: ->\lseries 

### ISSUE THREAD

**Issue by tudscr** [josephwright/siunitx#269] opened 2015-05-06 13:52 UTC
If `\seriesdefault`was set to `l` the package tries to use `\lseries` but this command is not provided by any class or package ASAIK.

    \documentclass{article}
    \usepackage{siunitx}
    \sisetup{detect-all}
    \def\seriesdefault{l}
    \begin{document}
    % the command \lseries is not defined
    \SI{-1984}{m^{-42}}
    \end{document}

**Comment by josephwright** [comment] 2015-05-06 13:53
Dupe of #268.

**Closed by josephwright** 2015-05-06 13:53 UTC
Labels: duplicate
