### ISSUE TITLE
rounding issue?

### ISSUE THREAD

**Issue by itzsimpl** [josephwright/siunitx#340] opened 2018-06-01 08:20 UTC
With 
```
	\sisetup{
		round-mode=figures,
		round-precision=3,
	}
```
the number
`\num{0.0001}` 
returns
`0.000100`

I am wandering if this is a bug or a feature.

**Comment by josephwright** [comment] 2018-06-01 11:00
Deciding what people expect when asked to round such cases is tricky: depending on the use case, it may or may not be appropriate to add additional zeros.

**Comment by itzsimpl** [comment] 2018-06-01 11:06
An idea could be to add a flag to either "add trailing zeros" or "not" and let the user decide.

**Comment by josephwright** [comment] 2018-06-12 17:38
I'm going to action this for v3: the work is ongoing and I'm on this very piece of code at the moment. Means it will be roughly the end of the year before it's available generally, but I think that's the best plan.

**Comment by josephwright** [comment] 2018-06-14 19:32
Ooh, I notice this is a duplicate of #274

**Closed by josephwright** 2018-06-14 19:32 UTC
Labels: enhancement
