### ISSUE TITLE
Asymmetrical uncertainties and round-mode w/ omit-uncertainty

### ISSUE THREAD

**Issue by parnmatt** [josephwright/siunitx#273] opened 2015-07-13 18:48 UTC
I have some thoughts, and wondered on your opinion.

---
# Rounding

`round-mode` will not round if there is an uncertainty component. I understand the reasoning behind that. However in context of `omit-uncertainty`, there is no uncertainty component, therefore this should round.

``` latex
    \num[round-mode=figures,round-precision=3]{1.2345(6)}
        % ==> 1.2345(6)
    \num[omit-uncertainty,round-mode=figures,round-precison=3]{1.2345(6)}
        % ==> 1.23
```

This is useful for me, as I am defining macros of full precision numbers with uncertainties and units etc. within my preamble, with an optional argument that sends the optional arguments to \SI
That way I have access to all the information if I want it, but reduce it when needed. Just as a random example, use-case, something like:

``` latex
    \newcommand*\amuValue[1][]{\SI[#1]{1.660538921(73)e−27)}{\kg}\xspace}
    % ...
    $\SI{1}{\amu} = \amuValue[omit-uncertainty,round-mode=figures,round-precison=3]$
```

but using `\amuValue` in multiple places within the document, including a table of constants with full precision.

---
# Asymmetrical uncertainties

A fair bit of the time our uncertainties are not symmetric, as they are not truly standard deviations.
I propose that these be incorporated, something like:

``` latex
    \num{number(min,max)}
    \num{number -min +max}
    \num{number +min -max}
```

Which would have something like what I've quickly written:

``` latex
    % useage:  \asymmnumerr{number}{min}{max}
    \newcommand*\asymmnumerr[3]{%
        \ensuremath{\num{#1}%
            _{\num[retain-explicit-plus,explicit-sign=-]{#2}}%
            ^{\num[retain-explicit-plus,explicit-sign=+]{#3}}%
    }}
```

**Comment by josephwright** [comment] 2017-04-11 13:13
I've just been reading _Nature_ and an example of the asymmetrical uncertainty case came up: I guess I do need to cover it! On rounding, I am working on some ideas for v3 and will have something there. I suspect I'll treat `omit-uncertainty` as a function of _display_ not _data_, so it will not directly impact.

**Comment by parnmatt** [comment] 2017-04-11 13:18
:+1: sounds good. I look forward to seeing how this turns out and how you incorporate the asymmetries.

**Comment by josephwright** [comment] 2017-04-11 14:02
@parnmatt  I guess the only question is the input syntax: probably your two models are right. I just have to adjust the internals (in v3) a little to allow for the extra data: not too hard really. The parsing is more complex (or rather telling it apart from a complex number is), but it's all doable.

**Comment by josephwright** [comment] 2017-04-11 16:26
@parnmatt As someone using this type of error representation, how do they normally 'come out'. The ones I've seen tend to have the same number of figures in each 'direction', so e.g. `7.0 +1.1 -0.5`. Is that normal? If so, I can model internally as a symmetrical error and an asymmetry, which would be convenient for me!

**Comment by parnmatt** [comment] 2017-04-12 14:03
Indeed. In fact it's incorrect to give errors to higher precision than the value you are quoting. 

`2` and `2.0` and `2.00` are three different values, as they directly imply the precision of the value/measurement. Thus you cannot say they are the same, but are compatible.

So in this case, the same precision should be used for the value and uncertainties.

`1.23 +0.45 -0.67` would be fine

`1.23 +0.456 -0.78` doesn't *really* make sense, to be 'valid' all should have the same precision `1.230 +0.456 -0.780`

**Comment by alex-shpilkin** [comment] 2018-02-07 17:41
@josephwright I saw you mentioning in [a TeX.SE comment](https://tex.stackexchange.com/q/108818/#comment238457_108818) that you did not understand asymmetrical uncertainties. In case it’s still relevant, here’s a short explanation.

Asymmetrical uncertainties often arise as asymmetrical confidence intervals, and these in turn are usually due to the reported value existing not on the real line but a half-line or a segment. For example, if you measured 4 decays in a certain time interval, it is meaningless to say that there should be 4±6 decays in intervals of that length, but you might well end up with a Bayesian estimate of 4<sup>+6</sup><sub>−2</sub> (numbers chosen arbitrarily). Then there are cases where the measuring equipment is truly asymmetrical: a detector might have “dark current”, meaning that it can record a certain (positive!) number of events even if nothing has happened; you may have a light/radiation/... background which is also necessarily positive; etc.

**Comment by josephwright** [comment] 2018-06-12 21:44
I've implemented "drop-uncertainty" as a clearer version of "omit-uncertainty" for v3: this addresses the first part of the request. 

On asymmetrical (non-Gaussian) uncertainties, my problems are that any input syntax is horrible, and it makes the internals _very_ tricky. I'm not really convinced on balance that this 'works', at least in a general set up. (I might yet consider a 'swappable' approach for such things.)

**Comment by wisp3rwind** [comment] 2018-06-13 16:54
I'd also like to see this feature implemented, it'd be rather unfortunate if no working input syntax could be found. What exactly is the issue? Maybe someone else can come up with a viable idea.

One way I could imagine is along the lines of
```tex
\num{1.234 \p 0.004 \m 0.010}
```
which would have some similarity to
```tex
\num{1.234 \pm 0.004}
```
and I guess parsing would be relatively straightforward.

**Comment by josephwright** [comment] 2018-06-13 17:58
@wisp3rwind Yes, but you also need an equivalent to `123(4)` but asymmetrical ... plus as I say some of my concerns are about internal structures. (Asymmetric uncertainties are _very_ specialised in the grand scheme of what I'm aiming to support.)

**Comment by josephwright** [comment] 2018-06-14 10:12
I think I can see how to handle this 'internally' (and #24): I'd like to ship v3 (already a big job), then will probably look at this for v3.1 (or at least I don't want to hold v3 purely for this area). There are various workable interfaces in my mind, but it's a question of what I can get going without *too* much code overhead for the 'common case' (no uncertainy at all).

**Comment by josephwright** [comment] 2018-06-21 09:30
I'm going to tackle this in two parts. For v3.0 I'll set up the internal number structure such that it can be extended to deal with different forms of uncertainty/error/tolerance. I'll then look at the printing/parsing for v3.1. I'm pushing this 'forward' as there is a lot to do for v3.0 and I'd like to get that out (and fix issues!) before adding what will be a major new feature.

**Comment by josephwright** [comment] 2018-06-21 10:12
I'm going to close here as a dupe of https://github.com/josephwright/siunitx/issues/24: that one is probably more 'focussed' (just one issue).

**Closed by josephwright** 2018-06-21 10:12 UTC
Labels: enhancement
