### ISSUE TITLE
Spurious show in \__siunitx_symbol_if_replace:NnTF

### ISSUE THREAD

**Issue by callegar** [josephwright/siunitx#480] opened 2021-06-09 22:07 UTC
The definition of `\__siunitx_symbol_if_replace:NnTF` does not match that in the code documentation and contains a
`\show\l__siunitx_symbol_tmpa_tl \show\l__siunitx_symbol_tmpb_tl` in the false path that causes the LaTeX compilation to hang.

**Comment by callegar** [comment] 2021-06-09 22:10
I see it is probably already fixed in git, sorry for the noise.

**Comment by josephwright** [comment] 2021-06-10 06:57
Duplicate of https://github.com/josephwright/siunitx/issues/478

**Closed** 2021-06-10 06:59 UTC
Labels: bug, duplicate
